### ISSUE TITLE
Improve how we call Twitch API

### ISSUE THREAD

**Issue by JoachimFlottorp** [hotbear1110/botbear#44]
The [Twitch API](https://dev.twitch.tv/docs/api) allows to query up to 100 users at a time on some of the api endpoints an example would be the /users.  
This would improve checking for name changes and checking if a streamer is live, checking for title and games, however we could look into removing these as these two functions are only used when the bot is turned on. [here](https://github.com/hotbear1110/botbear/blob/c9f7b2ea1b7f9c74853d8f5760cc92d4c1401179/bot.js#L566)

**Comment by hotbear1110** [comment]
Implimented this for namechanges in commit 6d17b94d2ea1db244c87723a4ad3ccffe41db388
